### ISSUE TITLE
GANDLF hash in setup for task_1 doesn't seem to pip install 

### ISSUE THREAD

**Issue by ambrishrawat** [FETS-AI/Challenge#172]
Hi, I tried using the `setup.py` and also independently installing GANDLF with pip,

`pip install GANDLF@git+https://github.com/CBICA/GaNDLF.git@e4d0d4bfdf4076130817001a98dfb90189956278`

but both get stuck on a git checkout. Was wondering if there's an alternate hash?

`git checkout -q e4d0d4bfdf4076130817001a98dfb90189956278`

**Comment by Gresliebear** [comment]
I am having the same issues  setup.py  

```
ERROR: Could not find a version that satisfies the requirement openfl (unavailable) (from fets-challenge) (from versions: 1.2, 1.2.1, 1.3)
ERROR: No matching distribution found for openfl (unavailable)
```

some other issues 
```
  hint: Disable this message with "git config advice.useCoreFSMonitorConfig false"
  Resolved https://github.com/intel/openfl.git to commit f4b28d710e2be31cdfa7487fdb4e8cb3a1387a5f
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\15702\AppData\Local\Temp\pip-install-licv3s62\openfl_030957633cd34b65a430368ab328bde9\setup.py", line 79, in <module>
          long_description = f.read()
        File "C:\Users\15702\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6189: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.        
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by phenomenal-manish** [comment]
> Hi, I tried using the `setup.py` and also independently installing GANDLF with pip,
> 
> `pip install GANDLF@git+https://github.com/CBICA/GaNDLF.git@e4d0d4bfdf4076130817001a98dfb90189956278`
> 
> but both get stuck on a git checkout. Was wondering if there's an alternate hash?
> 
> `git checkout -q e4d0d4bfdf4076130817001a98dfb90189956278`

Were you able to resolve this?

**Comment by phenomenal-manish** [comment]
@sarthakpati Can you please tell the fix to this?
The deadline for this challenge is very close.

**Comment by Geeks-Sid** [comment]
Hi All,

I am one of the devs from GANDLF.

I could not reproduce the same issue even with a fresh install. Could you please add your pip, git, and python version so that I could tackle it better?

I am adding my pip, git, GANDLF, and python version for cross-references. Additionally, the host operating system versions would also be helpful. I am currently running a UBUNTU 22.04 LTS 64-bit.

```
(test_env) siddhesh@siddhesh:~/Work/Projects/GANDLF/CBICA/GaNDLF$ pip --version
pip 21.2.4 from /home/siddhesh/miniconda3/envs/test_env/lib/python3.8/site-packages/pip (python 3.8)
(test_env) siddhesh@siddhesh:~/Work/Projects/GANDLF/CBICA/GaNDLF$ git --version
git version 2.34.1
(test_env) siddhesh@siddhesh:~/Work/Projects/GANDLF/CBICA/GaNDLF$ python --version
Python 3.8.13
(test_env) siddhesh@siddhesh:~/Work/Projects/GANDLF/CBICA/GaNDLF$ git status
HEAD detached at e4d0d4bf
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   GANDLF/OPM (modified content)
	modified:   GANDLF/anonymize/dicomanonymizer (modified content)

no changes added to commit (use "git add" and/or "git commit -a")
(test_env) siddhesh@siddhesh:~/Work/Projects/GANDLF/CBICA/GaNDLF$ gandlf_run --version
GANDLF v0.0.14-dev

Contact: gandlf@cbica.upenn.edu

This program is NOT FDA/CE approved and NOT intended for clinical use.
Copyright (c) 2022 University of Pennsylvania. All rights reserved.

Citation: https://arxiv.org/abs/2103.01006
```
I took the following steps to install the version
```
conda create -n test_env python=3.8 -y
conda activate test_env
conda install -c conda-forge mamba
pip3 install torch==1.8.2 torchvision==0.9.2 torchaudio==0.8.2 --extra-index-url https://download.pytorch.org/whl/lts/1.8/cu111
pip install GANDLF@git+https://github.com/CBICA/GaNDLF.git@e4d0d4bfdf4076130817001a98dfb90189956278
```
after all successful installs, this was my following output.
```
Installing collected packages: GANDLF
  Attempting uninstall: GANDLF
    Found existing installation: GANDLF 0.0.14.dev0
    Uninstalling GANDLF-0.0.14.dev0:
      Successfully uninstalled GANDLF-0.0.14.dev0
Successfully installed GANDLF-0.0.14.dev0
```
I would be actively responding to any queries for this thread moving forward.

**Comment by sunyeongan** [comment]
HI ! @Geeks-Sid , 
Let's discuss together @jingyunc
As you told me, I ran the command
 `pip install GANDLF@git+https://github.com/CBICA/GaANDLF.git@e4d0d4bfdf4076130817001a98dfb90189956278`.

A connection timeout error occurred

<img width="949" alt="Gandlf_error_0602" src="https://github.com/mlcommons/GaNDLF/assets/44018024/a54019f3-7483-4e6b-b955-945da8c884a3">

environment : window11 WSL2 Ubuntu linux 22.04

I'm curious, does that commit hash behind @ (e4d0d4bfdf4076130817001a98dfb90189956278`) still exist?

https://github.com/FeTS-AI/Challenge/blob/524d6b9f489ba852d601a437839abd937e5cab89/Task_1/setup.py#L32

If not, we will need to change the code above.

**Comment by jingyunc** [comment]
I confirm a successful installation of GaNDLF on UBUNTU 20.04, following @Geeks-Sid's post above.

**Comment by sarthakpati** [comment]
Thanks for helping out, @Geeks-Sid!
